name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "3 3 * * 2" # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # TODO: Re-enable when --ifdef no-indent works as intended
  # lint:
  #   name: Lint
  #   runs-on: macos-latest
  #   steps:
  #     - name: Git Checkout
  #       uses: actions/checkout@v5

  #     - name: Install SwiftFormat
  #       run: |
  #         brew unlink swiftformat
  #         brew install swiftformat --HEAD

  #     - name: SwiftFormat Lint
  #       run: swiftformat --lint . --reporter github-actions-log

  apple:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip ci]')
    name: ${{ matrix.platform }} (Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - mac-catalyst
          - macOS
          - tvOS
          - visionOS
          - watchOS
        swift:
          - "6.1"
          - "6.2"
        include:
          - swift: "6.1"
            runner: macos-15
          - swift: "6.2"
            runner: macos-26
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Select Xcode version
        uses: mxcl/xcodebuild@v3
        with:
          swift: ~${{ matrix.swift }}
          action: none
          verbosity: xcbeautify

      - name: Disable SwiftSyntax Prebuilts
        run: |
          defaults write com.apple.dt.Xcode IDEPackageEnablePrebuilts -bool NO

          # nuke cache to ensure it takes effect
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Developer/Xcode/SourcePackages
          rm -rf ~/Library/Caches/org.swift.swiftpm

      - if: ${{ matrix.platform != 'macOS' && matrix.platform != 'mac-catalyst' }}
        name: Initialize Simulator Service
        run: xcrun simctl list

      - if: ${{ matrix.platform != 'macOS' && matrix.platform != 'mac-catalyst' }}
        name: Download Default Runtime
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: xcodebuild -downloadPlatform ${{ matrix.platform }}

      - name: Run Tests
        uses: mxcl/xcodebuild@v3
        with:
          platform: ${{ matrix.platform }}
          swift: ~${{ matrix.swift }}
          action: test
          verbosity: xcbeautify

  linux:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip ci]')
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift:
          - "6.1"
          - "6.2"
        include:
          - swift: "6.1"
            image: swift:6.1
          - swift: "6.2"
            image: swiftlang/swift:nightly-6.2-jammy # swift:6.2 is stuck on 6.2.1, missing SwiftCompilerPlugin fix
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Run Tests
        run: swift test

  android:
    name: Android (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift:
          - "6.1"
          - "6.2"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Build and Test Library
        uses: skiptools/swift-android-action@v2
        with:
          swift-version: ${{ matrix.swift }}
          swift-build-flags: --disable-index-store
          swift-test-flags: --disable-index-store
          free-disk-space: true

  check-swift-syntax-compatibility:
    name: Swift Syntax Compatibility Check
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Run Swift Syntax Compatibility Check
        uses: davdroman/swift-macro-compatibility-check@from-version
        with:
          run-tests: false
          from-version: "601.0.0"
          major-versions-only: true
